services:

  cache:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - cgv_payment_network

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cgv_payment_network

  application:
    container_name: cgv-payment
    image: gothax2/ceos-payment:latest
    ports:
      - 8080:8080
    depends_on:
      - cache
      - postgres
    env_file:
      - .env
    networks:
      - cgv_payment_network

volumes:
  redis_data:
  postgres_data:

networks:
  cgv_payment_network:
    driver: bridge
