spring:
  profiles:
    include: local, jwt

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 800MB

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

etc:
  base-url: ${BASE_URL}

apikey:
  expiration:
    access: ${ACCESS_EXPIRATION}
  secret: ${JWT_SECRET}

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1_800_000}
    refresh: ${REFRESH_EXPIRATION:2_592_000_000}
  secret: ${JWT_SECRET:test1234tes1tte2st1234test1te!stte7stt@#e4sttes5ttest2testtest1234123415215161231}


logging:
  level:
    kr.co.loopz: debug

